buildscript {
    repositories {
        maven { url = "https://maven.minecraftforge.net" }
        jcenter()
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT"
    }
}

apply plugin: "net.minecraftforge.gradle.forge"

version = "1.0.0"
group = "ru.konyakpivo.bunmod"
archivesBaseName = "BunMod"

sourceCompatibility = targetCompatibility = "1.8"
compileJava.options.encoding = "UTF-8"

def minecraftVersion = "1.12.2"
def forgeVersion = "14.23.5.2847"

task printBuildInfo {
    doLast {
        println "Building BunMod for Minecraft ${minecraftVersion} with Forge ${forgeVersion}"
    }
}

minecraft {
    version = "${minecraftVersion}-${forgeVersion}"
    runDir = "run"
    mappings = "snapshot_20171003"
    makeObfSourceJar = false
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", minecraftVersion

    from(sourceSets.main.resources.srcDirs) {
        include "mcmod.info"
        expand "version": project.version, "mcversion": minecraftVersion
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }
}
